# Generated by Django 3.2.3 on 2021-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kalorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chory', models.FloatField()),
                ('blekka', models.FloatField()),
                ('lekka', models.FloatField()),
                ('srednia', models.FloatField()),
                ('duza', models.FloatField()),
                ('bduza', models.FloatField()),
            ],
        ),
    ]
